### PR TITLE
PR: Add latest version of ujson for py>3

### LINKED ISSUE #802: Adapt to ujson > 2.0
ujson 2.0 has been released, but this package requires <= 1.35 currently. Please update to the latest version.

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes https://github.com/palantir/python-language-server/issues/802

Ujson package has been revived and version 2.0 with wheels for all systems should be on PyPi shortly.

### CODE REVIEW

**Comment by yan12125** [comment]
ujson 3.0 is released and Windows and macOS wheels are included. However, that version drops supports for Python 2.7, which seems to be still supported by jsonrpc-server.

Release notes for ujson 3.0: https://github.com/ultrajson/ultrajson/releases/tag/3.0.0

**Comment by PureTryOut** [comment]
Is it dropping Python 2.7 support still an issue? Python 2.7 is EOL anyway and nobody should bother with it anymore really.

**Comment by PureTryOut** [comment]
Any chance this can be merged soon? It's currently blocking python-language-server on systems with newer ujson.

**Comment by ccordoba12** [comment]
Closing this one in favor of #44.

**Pull request closed without merging**
